### ISSUE TITLE
publish the latest contents

### ISSUE THREAD

**Issue by devoncarew** [google/tuple.dart#17]
We'll need a new publish of this package (as `1.0.3`). The pubspec and changelog have already been updated - we just need an uploader to publish the latest bits in master.

@kevmoo is the only uploader, and he's out for a bit.

@mit-mit can either you or @jonasfj upload?

cc @enetor for FYI

**Comment by kevmoo** [comment]
I can take care of it. I want to do a couple of tiny clean-ups first!

**Comment by enetor** [comment]
Thanks everyone!

**Comment by kevmoo** [comment]
> @kevmoo while you are at it, can you add at least one more publisher, just to avoid the single point of failure, pls?

invite set to you, @mit-mit !
