### ISSUE TITLE
[Proposal] Indexing tuples

### ISSUE THREAD

**Issue by KristianBalaj** [google/tuple.dart#23]
Hey nice work with the tuples 👋

I would like to propose a feature, to make the tuples indexable.

**Example:** 
```
final a = Tuple2(1, 2);
print(a[0].toString());
print(a[1].toString());
```
This code prints '1' and '2'.

- in case the index is out of bounds, the `RangeError` is thrown

You could assign me and I would do the PR.

**Comment by KristianBalaj** [comment]
Of course the indexing would be **just for getting** the values. (since the tuples are written in immutable fashion)

**Comment by M123-dev** [comment]
```
const t = const Tuple2<String, int>('a', 10);

print(t.item1); // prints 'a'
print(t.item2); // prints '10'
``` 

Isn't this snippet from the README.md what you meant only in a different form?
Maybe this is already because of your issue if so you can close this issue 😄

**Comment by znjameswu** [comment]
What would be the return type of `operator []` for `Tuple2<int, String>`? It's hard to reason.

**Comment by KristianBalaj** [comment]
@znjameswu yeah, you're right. That's a real problem.
We don't want dynamic return, I should close the issue then.
