### ISSUE TITLE
Set max SDK version to `<3.0.0`?

### ISSUE THREAD

**Issue by chalin** [google/tuple.dart#3]
@kevmoo - there is no upper bound on the SDK version, do you want it set for this package?

cc @kwalrath

**Comment by kevmoo** [comment]
CC @jcollins-g – this is not published. It's a copy used for our SDK.

**Comment by jcollins-g** [comment]
We should set it on the original and update the copy; pub package resolution is not used on SDK packages, but eventually it will be needed for the pub version of dartdoc
