### ISSUE TITLE
Should this package be deprecated/unlisted?

### ISSUE THREAD

**Issue by JaffaKetchup** [google/tuple.dart#45]
With the release of Dart 3.0 comes records. This pretty much does the same as this package, but has more advantages as it is more closely tied in with the other features of the language.

Is this package necessary anymore?

**Comment by oprypin** [comment]
While we are here-
In the world of records, is there an actual convenient alternative to `withItemN` methods?
E.g.

https://github.com/google/tuple.dart/blob/aac8fae64980f7c006109d850adfd36fcd09f49d/lib/tuple.dart#L154-L156

Or is there any way to write equivalent utility functions for records?
